# Generated by Django 2.2 on 2019-07-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangi', '0002_auto_20190727_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangi',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
